gmart_app/urls.py
# gmart_app URL Configuration

from django.urls import path
from .views import HomeView, add_to_cart, remove_from_cart
from . import views

# The urlpatterns list below routes URLs to their corresponding views.

urlpatterns = [
    path('', HomeView.as_view(), name='gmart-home'),
    path('about/', views.about, name='gmart-about'),
    path('product/<int:pk>', views.ProductDetailView.as_view(), name='gmart-product-detail'),
    path('add_to_cart/<int:pk>/<int:addQty>', add_to_cart, name='add-to-cart'),
    path('remove_from_cart/<int:pk>/<int:cart>', remove_from_cart, name='remove-from-cart'),
    path('gmart-cart/<int:pk>', views.OrderItemView.as_view(), name='gmart-cart'),
]

gmart_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('gmart_app.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gmart_app/models.py
from django.db import models
from django.conf import settings

#  Models:  https://docs.djangoproject.com/en/3.1/ref/models/fields/#model-field-types
#  List of Database Field Types:  https://docs.djangoproject.com/en/3.1/ref/models/fields/#model-field-types 


class Department (models.Model):
    Department_Name = models.CharField(max_length = 100, unique = True)

    def __str__(self):
        return self.Department_Name


class Product(models.Model):
    Product_Name = models.CharField(max_length = 100)
    Product_Department = models.ForeignKey(Department, on_delete = models.CASCADE)
    Product_Description = models.TextField()
    Product_Price = models.DecimalField(max_digits = 7, decimal_places = 2)
    Product_Quantity = models.IntegerField()
    Product_Highlights = models.TextField()
    Product_Details = models.TextField()
    Product_Image_Primary = models.ImageField(default='no_product.jpg', upload_to='product_images')

    def __str__(self):
        return f'{self.Product_Name} -- ${self.Product_Price}'


class Order(models.Model):
    Order_User = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    Order_Product = models.ManyToManyField(Product, through='OrderItem')
    Order_Created = models.DateTimeField(auto_now_add=True)
    Order_Date = models.DateTimeField()
    Order_Ordered = models.BooleanField(default=False)

    def __str__(self):
        return self.Order_User.username


class OrderItem(models.Model):
    OrderItem_Product = models.ForeignKey(Product, on_delete=models.CASCADE)
    OrderItem_Order = models.ForeignKey(Order, on_delete=models.CASCADE)
    OrderItem_Quantity = models.IntegerField(default=1)

    def __str__(self):
        return f'{self.OrderItem_Product}'

gmart_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.views.generic import ListView, DetailView
from django.contrib.auth.models import User
from .models import Product, OrderItem, Order, Department
import os, requests, datetime

# Initialize variables
dept_list = Department.objects.all()
specials_img_path='media/site_header_specials/'  # Path for carousel images
specials_img_list =os.listdir(specials_img_path)
cart_quantity = 0


def index(request):
    if request.user.is_authenticated:
        print("Logged in")
    else:
        print("Not logged in")

# The HomeView class inherits from the ListView class, allowing products to be displayed in list format, filtered by department.
class HomeView(ListView):
    model = Product
    template_name = "gmart_app/home.html"

    # Get Products
    def get_queryset(self):

        # Assume no Department was selected and get all Products
        queryset = Product.objects.all()
        dept_id = self.request.GET.get("dept")
        
        # Filter Products by Department if a Department was selected
        if dept_id:
            queryset = queryset.filter(Product_Department = dept_id)
        return queryset

    # Pass along each Context
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['img_specials'] = specials_img_list
        context['departments'] = dept_list
        context['cart_count'] = cart_quantity
        return context

# The OrderItemView inherits from the ListView class, which displays cart contents for the current user
class OrderItemView(ListView):
#if user is authenticated, then show their cart contents (get their rescent non-filled order's order_id to filter the order_item queryset)
    def get_queryset(self):
        template_name = "gmart_app/orderitem_list.html"
        if self.request.user.is_authenticated:
            if Order.objects.filter(Order_User=self.request.user, Order_Ordered=False).exists():
                # Return cart items
                cart_id = Order.objects.filter(Order_User=self.request.user, Order_Ordered=False)[0]
                queryset = OrderItem.objects.all().filter(OrderItem_Order_id = cart_id)
                self.cart_total = 0
                for prod in queryset:
                    prod.OrderItem_Total = prod.OrderItem_Quantity * prod.OrderItem_Product.Product_Price
                    self.cart_total += prod.OrderItem_Total
                if queryset.count() == 0:
                    messages.info(self.request, "Your cart is empty.")
            else:
                # Cart empty
                messages.info(self.request, "Your cart is empty.")
                queryset = OrderItem.objects.none()
        else:
            # User not logged in
            messages.info(self.request, "You must be logged in to access your cart.")
            queryset = OrderItem.objects.none()
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart_total'] = self.cart_total
        return context


# The ProductDetailView inherits from DetailView. 
# It provides product detail for a single product, using the product_detail.html page.
class ProductDetailView(DetailView):
    model = Product
    template_name = "gmart_app/product_detail.html"


# The about function displays the about.html page
def about(request):
    context = {}
    context['img_specials'] = specials_img_list
    return render(request, 'gmart_app/about.html', context)


# This function adds a specified quantity of a single product to the user's order
def add_to_cart(request, pk, addQty):
    if request.user.is_authenticated:
        # Get the selected product, using the pk passed into the function.
        selected_product = get_object_or_404(Product, id=pk)
        # Determine whether the cart already has an open order.
        if Order.objects.filter(Order_User=request.user, Order_Ordered=False).exists():
            cart_order = Order.objects.filter(Order_User=request.user, Order_Ordered=False)[0]
            # Determine whether the product is already in the cart.
            if OrderItem.objects.filter(OrderItem_Product=selected_product, OrderItem_Order=cart_order).exists():
                # Item alread in cart, add another by incrementing the quantity.
                cart_order_item = OrderItem.objects.get(OrderItem_Product=selected_product, OrderItem_Order=cart_order)
                cart_order_item.OrderItem_Quantity += addQty
                cart_order_item.save()
                messages.info(request, '%s added to your cart: %s' % (addQty, selected_product.Product_Name))
            else:
                # Item not in cart.  Create one.
                cart_order_item  = OrderItem.objects.create(OrderItem_Product=selected_product, OrderItem_Order=cart_order, OrderItem_Quantity=addQty)
                messages.info(request, '"%s" has been added to your cart.' % selected_product.Product_Name)
        else:
            # Create a new order and create a new item in the order
            new_order = Order.objects.create(Order_User=request.user, Order_Date=datetime.datetime.now())
            new_order_item = OrderItem.objects.create(OrderItem_Product=selected_product, OrderItem_Order=new_order, OrderItem_Quantity=addQty)
            messages.info(request, "This item has been added to your cart.")
        return redirect("gmart-product-detail", pk)
    else:
        messages.info(request, "This site is for members only.  Please login or register a new account.")
        return redirect("login")


# This function removes all quantities of a selected item from the cart.
def remove_from_cart(request, pk, cart):
    # There is no code in this function to maintain the cart's item count.  
        # Instead, there's a custom template tag to display the cart's item count... 
        # see cart_template_tags.py for details
    if OrderItem.objects.filter(pk = pk).exists():
        remove_item = OrderItem.objects.get(pk = pk).OrderItem_Product.Product_Name
        OrderItem.objects.get(pk = pk).delete()
        messages.info(request, '"%s" removed from cart.' % remove_item)
    else:
        messages.info(request, "Item not removed:  There was no matching item to remove from your cart.")
    return redirect("gmart-cart", cart)

gmart_app/templates/gmart_app/about.html
<!-- This page contains the "Behind The Scenes" content. -->

<!-- Insert this content within the base.html template. -->
{% extends "gmart_app/base.html" %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-auto">
      <img src="https://gmart-s3bucket.s3.amazonaws.com/design_images/ImgGear.png" width="230">
    </div>
    <div class="col-md-auto">
      <h1>Gmart</h1><h1>Behind the Scenes</h1>
    </div>
  </div>
</div>
<div class="container mt-3">
  <div class="row">
    <div class="col-lg-10 px-0">
      <div class="container">
        <h3>The Application</h3>
        <p>GMart is a storefront application developed in Python, from scratch, using the Django framework. It includes an implementation of the Django admin backend for managing products, categories and users. Additionally, a custom implementation of the authentication framework allows for front-end user account management.</p>
        <p>The storefront allows members to shop for products, storing selections in their shopping cart.  Members can view the contents of their carts, remove items, adjust quantities, etc.</p>
        <p>The application uses bootstrap for CSS styling throughout the site, including the carousel and card components for product presentation.</p>
        <p>And finally, vanilla javascript is used to create dynamic increase/decrease buttons to modify product quantities in the DOM, which are passed back to Django, creating dynamic SPA-type functionality for an improved user experience. </p>
        <h3>The Deployment</h3>
        <p>GMart has been deployed to a cloud environment, on the AWS platform.  The project is maintained with version control, using GIT, and pushed to a Github repository.  AWS deployment is configured with a CodePipeline to automatically recognize and deploy changes from the Github repository. </p>
      </div>
    </div>
    <div class="col-lg-2 mt-5">
      <img src="https://gmart-s3bucket.s3.amazonaws.com/design_images/LogoDjango.png" width="100">
      <img src="https://gmart-s3bucket.s3.amazonaws.com/design_images/LogoPython.png" width="100">
      <img src="https://gmart-s3bucket.s3.amazonaws.com/design_images/LogoBootstrap.png" width="100">
      <img src="https://gmart-s3bucket.s3.amazonaws.com/design_images/Logo-Javascript-HTML-CSS.jpg" width="100">
      <img src="https://gmart-s3bucket.s3.amazonaws.com/design_images/LogoAWS01.png" width="100">
      <img src="https://gmart-s3bucket.s3.amazonaws.com/design_images/LogoGit.png" width="100">
      <img src="https://gmart-s3bucket.s3.amazonaws.com/design_images/LogoGitHub.png" width="100">
    </div>
  </div>
  <a class="btn btn-primary" href="{% url 'gmart-home' %}" width="500px">Return to GMart</a>
</div>

{% endblock content %}

gmart_app/templates/gmart_app/base.html
<!-- Base Template for providing common layout for every web page -->

{% load static %}  <!-- Load files out of the static folder -->
{% load cart_template_tags %}  <!-- Custom template tags for tracking things like the number of items in the cart-->


<!DOCTYPE html>
<html>
    <head>

        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <!-- link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'gmart_app/main.css' %}">  <!--- Generate an absolute URL to the static folder and pulls in the stylesheet -->
        <!-- Bootstrap Styling Examples:  https://getbootstrap.com/docs/4.5/examples/ -->

        <!-- Pull in the requred javascript for the "Product Hover Zoom" functionality -->
        {% include 'gmart_app/product_hover_zoom.html' %}

        <!-- Display the page title, if there is one -->
        {% if title %}
            <title>GMart - {{ title }}</title>
        {% else %}
            <title>GMart</title>
        {% endif %}
    </head>
    <body oncontextmenu='return false' class='snippet-body'>
        <header class="site-header">
            <!-- Horizontal Navigation Bar across the top of the website -->
            <nav class="navbar fixed-top navbar-expand-md navbar-dark bg-steel">
                <div class="container">
                    <a class="navbar-brand mr-4" href="{% url 'gmart-home' %}">GMart</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarToggle">
                        <!-- Navbar Left Side -->
                        <div class="navbar-nav mr-auto">
                            <a class="nav-item nav-link" href="{% url 'gmart-home' %}">Home</a>
                            <a class="nav-item nav-link" href="{% url 'gmart-about' %}">Behind-The-Scenes Tour</a>
                        </div>
                        <!-- Navbar Right Side -->
                        <div class="navbar-nav">
                            <!-- Based on authentication, display login/logout and welcome/register -->
                            {% if user.is_authenticated %}
                                <!-- The Welcome Username link sends the user to the update profile page -->
                                <a class="nav-item nav-link" href="{% url 'profile' %}"> Welcome {{ user.username }}</a>
                                <!-- The Logout link will logout the user -->
                                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                            {% else %}
                                <!-- The Login link sends the user to the Login page -->
                                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                                <!-- The Register link sends the user to the registration page to create an account -->
                                <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                            {% endif %}
                            <a href="{% url 'gmart-cart' 5 %}">
                                <img width=30 src="{% static 'gmart_app/shopping-cart-icon.png' %}" alt="View Cart">
                                <!-- Use a custom template tag to display the cart's item count... see cart_template_tags.py for details -->
                                <p class="badge badge-pill badge-danger p-1 top-0 start-0">{{ request.user|cart_item_count }}</p>
                            </a>
                        </div>
                    </div>
                </div>
            </nav>
        </header>
        <main role="main" class="container">
            <div class="row">
                <!-- Div container for displaying messages -->
                <div class="col-md-9">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }}"> <!-- Django and Bootstrap messages use same naming convention, so we can use message.tags -->
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}

                    <!-- Each content page will be inserted here -->
                    {% block content %}{% endblock %}

                </div>
                <!-- List of departments for filtering products by department -->
                {% if departments %}
                <div class="col-md-3">
                    <div class="content-section">
                    <h4>Departments</h4>
                        <p class='text-muted'>
                            {% for dept in departments %}
                            <a href="/?dept={{ dept.id }}" class="p-1 list-group-item list-group-item-action">{{ dept.Department_Name }}</a>
                            {% endfor %}
                        </p>
                    </div>
                </div>
                {% endif %}
            </div>
        </main>
        <!-- Required JavaScript for Bootstrap styling -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>

        <!-- Load the JavaScript code for this website -->
        <script src="{% static 'gmart_app/app.js' %}"></script>
    </body>
</html>

gmart_app/templates/gmart_app/home.html
{% extends "gmart_app/base.html" %}
{% block content %}

<div>
    <!-- Bootstrap 4.0 Carousel -->
    <div id="carouselSpecials" class="carousel slide m-1" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselSpecials" data-slide-to="0" class="active"></li>
            <li data-target="#carouselSpecials" data-slide-to="1"></li>
            <li data-target="#carouselSpecials" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            {% for next_image in img_specials %}
            {% if next_image == "FirstCarouselSlide.png" %}
            <!-- The first carousel slide must have a class of "active", therefore it is named "FirstCarouselSlide.png" for identification purposes -->
            <div class="carousel-item active">
                <img class="d-block w-100" src="https://gmart-s3bucket.s3.amazonaws.com/site_header_specials/{{next_image}}" alt="Hot Specials">
                <!-- Optionally, text overlays can be placed over each image as follows: 
                <div class="carousel-caption d-none d-md-block">
                    <h5>My Caption Title (1st Image)</h5>
                    <p>Additional text that will only show up if the screen is at least medium size.</p>
                </div>
                -->
            </div>            
            {% else %}
            <!-- All other subsequent slides are loaded into the carousel -->
            <div class="carousel-item">
                <img class="d-block w-100" src="https://gmart-s3bucket.s3.amazonaws.com/site_header_specials/{{next_image}}" alt="Hot Specials">
            </div>        
            {% endif %}
            {% endfor %}
        </div>
        <!-- Carousel Controls for sliding through images -->
        <a class="carousel-control-prev" href="#carouselSpecials" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselSpecials" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>

<!-- Display Products -->
<div class="col-md-12">
    {% include 'gmart_app/product_list.html' %}
</div>


{% endblock content %}

gmart_app/templates/gmart_app/orderitem_list.html
{% extends "gmart_app/base.html" %}
{% block content %}
{% load humanize %}

{% if object_list.count > 0 %}
<div>
    <table>
        <!-- Items currently in cart -->
        <tr>
            <td>
                <h4>Items in Cart</h4>
            </td>
        </tr>
        <tr>
            <td>
                <table class="table">
                <!-- Loop through each item in the cart and display the product image, quantity and details. -->
                {% for prod in object_list %}
                    <tr>
                        <td height="100">
                            <img height="100" src="{{ prod.OrderItem_Product.Product_Image_Primary.url }}" alt="{{ prod.OrderItem_Product.Product_Name }}">
                        </td>
                        <td>
                            <div>
                                <h4>{{ prod.OrderItem_Product.Product_Name }}</h4>
                            </div>
                            <!-- Display Quantity X Price = Total -->
                            <div>
                                <h5>{{ prod.OrderItem_Quantity }} @ ${{ prod.OrderItem_Product.Product_Price|intcomma }}ea 
                                    = ${{ prod.OrderItem_Total|intcomma }}
                                    
                                </h5>
                            </div>
                            <!-- Provide an option to remove or add items to the cart -->
                            <div>
                                <a class="btn btn-primary" href="{% url 'gmart-product-detail' prod.OrderItem_Product.id %}">Add More</a>
                                <a class="btn btn-primary" href="{% url 'remove-from-cart' prod.id prod.OrderItem_Order_id %}">Remove All</a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
                </table>
            </td>
        </tr>
        <!-- Order Summary, including list of products, quantities, prices and totals -->
        <tr>
            <td>
                <br><br><h4>Order Summary</h4>
            </td>
        </tr>
        <tr>
            <td>
                <table>
                    <tr>
                        <td>
                            <tr class="bg-secondary text-white">
                                <th class="p-1">
                                    Product
                                </td>
                                <th class="p-1">
                                    Quantity
                                </td>
                                <td class="p-1"> </td>
                                <th class="p-1 text-right">
                                    Total
                                </td>
                            </tr>{% for prod in object_list %}
                            <tr class="bg-secondary text-white">
                                <td class="p-1">
                                    {{ prod.OrderItem_Product.Product_Name }}
                                </td>
                                <td class="p-1">
                                    {{ prod.OrderItem_Quantity }} @ ${{ prod.OrderItem_Product.Product_Price|intcomma }}ea
                                </td>
                                <td class="p-1">=</td>
                                <td class="p-1 text-right">
                                    ${{ prod.OrderItem_Total|intcomma }} 
                                </td>
                            </tr>
                            {% endfor %}
                            
                            <tr>
                                <td class="p-1">
                                </td>
                                <td class="p-1 text-right"> 
                                </td>
                                <td class="p-1">=</td>
                                <td class="p-1 text-right">
                                    ${{ cart_total|intcomma }}
                                </td>
                            </tr>
                        </td>
                    </tr>

                </table>
            </td>
        </tr>
        <!-- Option to checkout or continue shopping -->
        <tr>
            <td>
                <div>
                    <a class="btn btn-primary" href="{% url 'gmart-home' %}">Continue Shopping</a>
                    <a class="btn btn-primary" onclick="eCommercePlaceholder()">Proceed to Checkout</a>
                </div>
            </td>
        </tr>
    </table>
</div>
{% endif %}



{% endblock content %}

gmart_app/templates/gmart_app/product_detail.html
<!-- This page includes Product Detail content and is inserted into the base.html template. -->

{% extends "gmart_app/base.html" %}
{% block content %}

<script type="text/javascript" src="https://res.cloudinary.com/dxfq3iotg/raw/upload/v1565190285/Scripts/xzoom.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://res.cloudinary.com/dxfq3iotg/raw/upload/v1565190284/Scripts/xzoom.css" media="all" />
<div class="container d-flex justify-content-center border">
    <section id="default" class="padding-top0">
        <div class="row">
            <div class="large-5 col-md-6">
                <div class="xzoom-container"> 
                    <!-- Display the selected image in its original size -->
                    <img class="xzoom" width="400px" id="xzoom-default" src="{{ object.Product_Image_Primary.url }}" xoriginal="{{ object.Product_Image_Primary.url }}" />
                    <!-- Display the non-selected images as thumbnails for selecting -->
                    <div class="xzoom-thumbs"> 
                        <a href="{{ object.Product_Image_Primary.url }}"><img class="xzoom-gallery" width="80" src="{{ object.Product_Image_Primary.url }}" xpreview="{{ object.Product_Image_Primary.url }}"></a>
                        <a href="https://res.cloudinary.com/dxfq3iotg/image/upload/v1565190720/gallery/original/02_o_car.jpg"><img class="xzoom-gallery" width="80" src="https://res.cloudinary.com/dxfq3iotg/image/upload/v1565190720/gallery/preview/02_o_car.jpg"></a> 
                        <a href="https://res.cloudinary.com/dxfq3iotg/image/upload/v1565190718/gallery/original/03_r_car.jpg"><img class="xzoom-gallery" width="80" src="https://res.cloudinary.com/dxfq3iotg/image/upload/v1565190715/gallery/preview/03_r_car.jpg"></a> 
                        <a href="https://res.cloudinary.com/dxfq3iotg/image/upload/v1565190717/gallery/original/04_g_car.jpg"><img class="xzoom-gallery" width="80" src="https://res.cloudinary.com/dxfq3iotg/image/upload/v1565190714/gallery/preview/04_g_car.jpg"></a> 
                    </div>
                </div>
            </div>
            <!-- Display product details and Quantity Selectors -->
            <div class="col-md-6">
                <div class="p-1 mt-5">

                    <!-- Product Details-->
                    <h5>{{ object.Product_Name }}</h5>
                    <p>{{ object.Product_Description|linebreaks }}</p>
                    <p class="font-weight-bold">Product Highlights:</p>
                    <p>{{ object.Product_Highlights|linebreaks }}</p>
                    <p class="font-weight-bold">Product Details:</p>
                    <p>{{ object.Product_Details|linebreaks }}</p>

                    <div class="mt-auto text-center">
                        <h6>Price Each:  ${{ object.Product_Price }}</h6>
                        <!-- Quantity Selector:  buttons to increase and decrease item quantity -->
                        <h6 id="quantity-selector">Quantity:  
                            <button type="button" class="btn btn-outline-primary btn-tiny" id="quantity-decrease">&#x25Bc;</button>
                            <span id="item-quantity">1</span> 
                            <button type="button" class="btn btn-outline-primary btn-tiny" id="quantity-increase">&#x25B2;</button>
                        </h6>
                        <a class="btn btn-primary" href="{% url 'gmart-home' %}" width="500px">Cancel</a>
                        <!-- Display the "Add To Cart" button, and specify the quantity on the button. -->
                        <a class="btn btn-primary" id="add-to-cart" href="{% url 'add-to-cart' object.id 555 %}">Add 1 to Cart</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>


{% endblock content %}

gmart_app/templates/gmart_app/product_list.html
<!-- GR. Images:  See notes at bottom of page regaring how product images are handled -->

<!-- Loop through each product and present its details in a bootstrap card.  
    Organize each card in a bootstrap flexbox grid of rows and columns. 
-->
<div class="card-group">
    {% for prod in object_list %}
    {% if forloop.counter0|divisibleby:3 %} <div class="row"> {% endif %}
    <div class="card col-md-4 m-0 p-0 border-0">
        <div class="card m-1 h-100">
            <a href="{% url 'gmart-product-detail' prod.id %}" class="list-group-item list-group-item-action border-0 p-0 m-0">
                <div class="card-header text-center p-2 h5 m-0">
                    {{ prod.Product_Name }}
                </div>
                <div class="card-body d-flex flex-column">
                    <img src="{{ prod.Product_Image_Primary.url }}" class="card-img-top" alt="Product Image">
                    {{ prod.Product_Description }}
                </div>
            </a>
            <div class="mt-auto text-center p-2">
                <h6>${{ prod.Product_Price }}</h6>
                <a class="btn btn-primary" href="{% url 'gmart-product-detail' prod.id %}">View Details</a>
            </div>
        </div>
    </div>
    {%  if forloop.counter|divisibleby:3 or forloop.last %}</div>{% endif %}
    {% endfor %}
</div>



<!-- GR. Product Images
    Product Images in the Development Environment require a different setup than deployment into a production environment
    Product Images are handled with the Pillow library.
    In addition to installing and importing the Pillow library, the MEDIA_ROOT and MEDIA_URL settings
        are defined in the Project's settings.py file.
    And then we add MEDIA routes to URLs in the Project's urls.py file
-->